### ISSUE TITLE
Enhanced link configuration options for buttons and images

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#1]
Many of our clients reported that they would expect the link toolbox work similarly like they saw it in ckEditor. This means that the protocol could be selectable, and there would be an "other" option there, which would not force any protocol on the link itself. (All of the selectable options: http://, https://, ftp:// <other>)

Also, it's expected to behave in the same way in the image's toolbox.

**Comment by gyulanemeth** [comment]
To finalize this enhancement, we need the localization values for the following two words:
- Protocol,
- Other

**Comment by PedroL-btl** [comment]
PT:  protocol:protocolo, other:outro.

**Comment by agnieszkakowalska** [comment]
zh-HANS: protocol: 协议, other: 其他
FR: protocol: protocole, other: autre
PL: protocol: protokół, other: inny
RU: protocol: протокол, other: другой

**Comment by m33ch** [comment]
IT : protocol : protocollo, other : altro

**Comment by gyulanemeth** [comment]
https://github.com/EDMdesigner/editor-issues/releases/tag/r20160219
