### ISSUE TITLE
Paragraph Spacing in editor version r20160219

### ISSUE THREAD

**Issue by leggomuhgreggo** [EDMdesigner/editor-issues#10]
Hello!

I swapped to the new editor version today and noticed a bug. When actively editing a text element I could make spacing between paragraphs by hitting enter, creating a `<p>` tag with a nested `&nbsp` but when I left the active state for editing the text the spacing between text blocks collapsed, and it was also collapsed in the preview. Took some screenshots.

Working normally in text edit active state:
http://i.imgur.com/SGEDJZe.png

Collapsed when not actively editing text:
http://i.imgur.com/73DBZET.png

Looks like the `&nbsp;` is being removed

Switch back a version and it's working.

Thanks!

**Comment by leggomuhgreggo** [comment]
Also, it'd be baller if a cookie could be set so that alerts of new editor availability wouldn't show every refresh.

**Comment by gyulanemeth** [comment]
Hello,

yes, we have noticed this bug as well. I will look into it this afternoon and hopefully I can hotfix it in this editor version.

**Comment by gyulanemeth** [comment]
Hotfixed in https://github.com/EDMdesigner/editor-issues/releases/tag/r20160219
