### ISSUE TITLE
Image + Text / Text + Image issue is editor r20160219

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#11]
Dear Gyula,

In editor r20160219, when using image + text block / text + image block, the text edited cannot save.

e.g. when edited the text block and click "Export" button directly below, **we manually call save project, and a "Save result: success" message returned by edmdesigner**:
![2016-02-22_15-41-54](https://cloud.githubusercontent.com/assets/5524183/13212280/e3286878-d97a-11e5-8e86-dd65b9e04628.jpg)

After that we export the html by api, the html output still showing old version:
![2016-02-22_15-44-00](https://cloud.githubusercontent.com/assets/5524183/13212308/1d1c76dc-d97b-11e5-8262-51f99881882c.jpg)

Please help check, thanks.

**Comment by gyulanemeth** [comment]
Thank you for reporting this, we will investigate and fix it in our next sprint starting on Wednesday.

**Comment by balintsoos** [comment]
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by gyulanemeth** [comment]
As I experienced it, we just have to make sure that the autosave is switched off and we have to wait for the "Save success." message after sending Save manually into the iframe.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
