### ISSUE TITLE
Wrong text "hide on mobile/desktop"

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#111]
We found that the wrong text appears in the editor in the box settings.

If you point to the text "Hide on desktop:" in the "Mobile settings" section, the text "Hide on mobile:" while be displayed while "Hide on desktop:" should be displayed.
Look at screencast - http://take.ms/mR7qx

A similar problem in the Russian interface. When hovering on the "скрывать на компьютере" is displayed "скрывать на телефоне" and should be "скрывать на компьютере".

Could you please fix it?

**Comment by smiska** [comment]
Hi,

Thanks for the feedback.

Please check it in the upcoming editor release (expected this week) when the dashboard notification shows that the release was issued.

Thanks.

**Comment by agnieszkakowalska** [comment]
Hi, could you please tell me in which version of editor was it released?

**Comment by agnieszkakowalska** [comment]
Hi @smiska is this fix already released? I can see that the latest version in Dashboard to choose is 20180705.

**Comment by agnieszkakowalska** [comment]
@smiska I'll appreciate your answer.
