### ISSUE TITLE
Constant Invalid HTML response for imports

### ISSUE THREAD

**Issue by samanthazen1210** [EDMdesigner/editor-issues#112]
We are getting an Invalid HTML for all HTML imports currently, even with code that has previously imported just fine (i.e. we often use this for testing: https://github.com/leemunroe/responsive-html-email-template). Is there anything going on with the import process?

**Comment by smiska** [comment]
Hi, could you provide further reproduction steps, possibly a screencast on how this happens?
Thanks.

**Comment by samanthazen1210** [comment]
Hi, we now have an ongoing email ticket with Roland and Gyula.
