### ISSUE TITLE
Rendering issue with hyperlinked buttons - Links do not work

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#116]
We are seeing an issue where when rendering a preview email, the link in the button frequently doesn't work.

I have a saved template and I sent a preview - the link on the button works.  With no changes made, I previewed again and the link didn't work in the second email.  Viewing the source HTML in both emails, they are different.

**1st preview with working link**
```
<td valign="top" align="center" style="padding-top: 10px;padding-right: 40px;padding-bottom: 10px;padding-left: 40px;"><a href="http://www.gold-vision.com" target="_blank" style="text-decoration: none;" class="edm_button"><span style="font-family: arial;font-size: 14px;color: #000000;line-height: 14px;text-decoration: none;"><span style="color: #ffffff; font-family: arial;">Read about it here</span></span> </a></td>
```

**2nd preview where the link doesn't work**
```
<td valign="top" align="center" style="padding-top: 20px;padding-right: 10px;padding-left: 10px;">
<a href="http://www.gold-vision.com" target="_blank" style="display: inline-block;text-decoration: none;">
<table cellpadding="0" cellspacing="0" border="0" bgcolor="#008BA6" style="border: 1px solid #008BA6;background-color: #008BA6;" class="full-width">
<tr>
<td align="center" style="padding-top: 10px;padding-right: 40px;padding-bottom: 10px;padding-left: 40px;">
<span style="color: #000000 !important;font-family: arial;font-size: 14px;mso-line-height: exactly;line-height: 14px;">
<font color="#000000">
<span style="text-align: center;"><span style="color: #ffffff; font-family: arial;">Read about it here</span></span>
</font>
</span>
</td>
```

Is this a known issue?  How can we resolve it?

**Comment by gyulanemeth** [comment]
Hello,

Where did it not work? I'm suspecting in mso outlook versions. You will have to use the unsanitized route for generating the email html.

**Comment by GVSupport** [comment]
Hi

In the designer I sent a preview of the template.  I sent another preview of the same template two minutes later having made no changes to the design.

The HTML forming the button and hyperlink was different in each email, which does not make sense.  You can see the two examples of the HTML in the Github ticket.

Why would the HTML be formed differently for two previews from the same template?

Thanks

Russell Jackson

Gold-Vision CRM    Senior Technical Support Consultant
rjackson@gold-vision.com<mailto:rjackson@gold-vision.com>
UK +44 (0)1788 511 110   North America +1 (647) 494 9870   Toll Free +1 (877) 673 1230
Twitter<https://twitter.com/goldvisioncrm> | LinkedIn<https://www.linkedin.com/company/esteiro-business-solutions-limited> | Facebook<https://www.facebook.com/goldvisioncrm/> | gold-vision.com<https://www.gold-vision.com>

[Arrange your upgrade today.]<https://gvhelp.goldvisioncrm.com/gol/arrange-your-gold-vision-8-upgrade/?utm_source=signature&utm_medium=email&utm_campaign=arrange-your-upgrade;utm_content=rjackson>

The contents of this email are private and for the use of the intended recipient in accordance with our Privacy Notice<https://www.gold-vision.com/privacy-notice>. If this email has been delivered to you in error, please let us know and delete the email. All outgoing email is scanned for viruses, however, we cannot guarantee full protection. Gold-Vision is the trading name of Esteiro Business Solutions Ltd., located at Unit 4-6 Ryehills Lane, West Haddon, Northants, NN6 7BX, UK. Reg. 04292582

**Comment by gyulanemeth** [comment]
Hello,

we released a button enhancement that will make the whole button clickable on all email clients but outlook. We introduced a fallback mechanism for outlook, but that requires everyone to use the generator without sanitizing.

We are checking right now if it's safe to make the without sanitizing the default option.

**Comment by gyulanemeth** [comment]
We are running our final tests and I'm very confident that we will release the fix very early tomorrow.

**Comment by GVSupport** [comment]
Thank you.

Do you have any news on this please as we have a collection of customer support issues reported for this.

Regards

Mark

Mark Vernon

Gold-Vision CRM    Head of Product Development
mjvernon@gold-vision.com<mailto:mjvernon@gold-vision.com>
UK +44 (0)1788 511 110   North America +1 (647) 494 9870   Toll Free +1 (877) 673 1230
Twitter<https://twitter.com/goldvisioncrm> | LinkedIn<https://www.linkedin.com/company/esteiro-business-solutions-limited> | Facebook<https://www.facebook.com/goldvisioncrm/> | gold-vision.com<https://www.gold-vision.com>

[Your CRM, your way - find out more]<https://www.gold-vision.com/?utm_source=signature&utm_medium=email&utm_campaign=your-crm-your-way;utm_content=mjvernon>

The contents of this email are private and for the use of the intended recipient in accordance with our Privacy Notice<https://www.gold-vision.com/privacy-notice>. If this email has been delivered to you in error, please let us know and delete the email. All outgoing email is scanned for viruses, however, we cannot guarantee full protection. Gold-Vision is the trading name of Esteiro Business Solutions Ltd., located at Unit 4-6 Ryehills Lane, West Haddon, Northants, NN6 7BX, UK. Reg. 04292582

**Comment by GVSupport** [comment]
Hi Gyula,

Do you have any update on this please?

Thanks

Mark

Mark Vernon

Gold-Vision CRM    Head of Product Development
mjvernon@gold-vision.com<mailto:mjvernon@gold-vision.com>
UK +44 (0)1788 511 110   North America +1 (647) 494 9870   Toll Free +1 (877) 673 1230
Twitter<https://twitter.com/goldvisioncrm> | LinkedIn<https://www.linkedin.com/company/esteiro-business-solutions-limited> | Facebook<https://www.facebook.com/goldvisioncrm/> | gold-vision.com<https://www.gold-vision.com>

[Your CRM, your way - find out more]<https://www.gold-vision.com/?utm_source=signature&utm_medium=email&utm_campaign=your-crm-your-way;utm_content=mjvernon>

The contents of this email are private and for the use of the intended recipient in accordance with our Privacy Notice<https://www.gold-vision.com/privacy-notice>. If this email has been delivered to you in error, please let us know and delete the email. All outgoing email is scanned for viruses, however, we cannot guarantee full protection. Gold-Vision is the trading name of Esteiro Business Solutions Ltd., located at Unit 4-6 Ryehills Lane, West Haddon, Northants, NN6 7BX, UK. Reg. 04292582
From: Gold-Vision Support
Sent: 30 October 2019 10:07
To: EDMdesigner/editor-issues <reply@reply.github.com>; EDMdesigner/editor-issues <editor-issues@noreply.github.com>
Cc: Gold-Vision Support <support@gold-vision.com>; Author <author@noreply.github.com>
Subject: RE: [EDMdesigner/editor-issues] Rendering issue with hyperlinked buttons - Links do not work (#116)

Thank you.

Do you have any news on this please as we have a collection of customer support issues reported for this.

Regards

Mark

Mark Vernon

Gold-Vision CRM    Head of Product Development
mjvernon@gold-vision.com<mailto:mjvernon@gold-vision.com>
UK +44 (0)1788 511 110   North America +1 (647) 494 9870   Toll Free +1 (877) 673 1230
Twitter<https://twitter.com/goldvisioncrm> | LinkedIn<https://www.linkedin.com/company/esteiro-business-solutions-limited> | Facebook<https://www.facebook.com/goldvisioncrm/> | gold-vision.com<https://www.gold-vision.com>

[Your CRM, your way - find out more]<https://www.gold-vision.com/?utm_source=signature&utm_medium=email&utm_campaign=your-crm-your-way;utm_content=mjvernon>

The contents of this email are private and for the use of the intended recipient in accordance with our Privacy Notice<https://www.gold-vision.com/privacy-notice>. If this email has been delivered to you in error, please let us know and delete the email. All outgoing email is scanned for viruses, however, we cannot guarantee full protection. Gold-Vision is the trading name of Esteiro Business Solutions Ltd., located at Unit 4-6 Ryehills Lane, West Haddon, Northants, NN6 7BX, UK. Reg. 04292582

**Comment by iamgaborgithub** [comment]
Hello @GVSupport 

We changed the default behavior of our generator. From now we don't sanitize the code.
We did it because that sanitization caused the issue with the button yesterday and also some issues in the past.

If you have problems because of this change, please let me know and we will help you.

Could you please test the preview that you mentioned again to be sure about our fix works for you as well?

Kind regards,
Gábor
Project Manager @ EDMdesigner.com

**Comment by GVSupport** [comment]
Thank you for the update.  It appears ok from our end.

Mark Vernon

Gold-Vision CRM    Head of Product Development
mjvernon@gold-vision.com<mailto:mjvernon@gold-vision.com>
UK +44 (0)1788 511 110   North America +1 (647) 494 9870   Toll Free +1 (877) 673 1230
Twitter<https://twitter.com/goldvisioncrm> | LinkedIn<https://www.linkedin.com/company/esteiro-business-solutions-limited> | Facebook<https://www.facebook.com/goldvisioncrm/> | gold-vision.com<https://www.gold-vision.com>

[Your CRM, your way - find out more]<https://www.gold-vision.com/?utm_source=signature&utm_medium=email&utm_campaign=your-crm-your-way;utm_content=mjvernon>

The contents of this email are private and for the use of the intended recipient in accordance with our Privacy Notice<https://www.gold-vision.com/privacy-notice>. If this email has been delivered to you in error, please let us know and delete the email. All outgoing email is scanned for viruses, however, we cannot guarantee full protection. Gold-Vision is the trading name of Esteiro Business Solutions Ltd., located at Unit 4-6 Ryehills Lane, West Haddon, Northants, NN6 7BX, UK. Reg. 04292582
