### ISSUE TITLE
0x0px image size issue in custom gallery

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#14]
There is still an issue with images in custom gallery -after adding an image, it has size 0x0px and only after going to another element and going back, it is possible to change the size.

**Comment by balintsoos** [comment]
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
