### ISSUE TITLE
Large preview of image

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#17]
I don't know if it affects only custom gallery, but when I add an image, its preview is very large in version r20160219:
![2016-03-01 09_00_54-zdjecia](https://cloud.githubusercontent.com/assets/17157918/13421104/4da97c66-df8c-11e5-95b9-b19c93d4a0ed.png)

comparing to the previous version:
![2016-03-01 09_00_14-zdjecia](https://cloud.githubusercontent.com/assets/17157918/13421113/615f4b5a-df8c-11e5-805d-25ad99c768ea.png)

Checked in FF.

**Comment by balintsoos** [comment]
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
