### ISSUE TITLE
switching between tabs is not working correctly

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#18]
When I add an image to the template and change tab to default, then I'm not able to come back to Content tab again unless I select other element and go back to image.
Video here: https://chruu.tinytake.com/sf/NDQyMzczXzIzOTg1NTM

**Comment by balintsoos** [comment]
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
