### ISSUE TITLE
G+ logo incorrect

### ISSUE THREAD

**Issue by GVPenni** [EDMdesigner/editor-issues#20]
Incorrect logo's offered in tool - they have since updated.

![btn_google _dark_normal_ios - copy](https://cloud.githubusercontent.com/assets/17725108/13603958/7c6f15c2-e538-11e5-979e-c35a90051c61.png)

![btn_google _dark_normal_ios](https://cloud.githubusercontent.com/assets/17725108/13603962/7f05bcc8-e538-11e5-8ca0-7e9389ab223e.png)
![btn_google _dark_normal_ios 2x - copy](https://cloud.githubusercontent.com/assets/17725108/13603964/80d0a450-e538-11e5-8407-1cce39f9400f.png)
![btn_google _dark_normal_ios 2x](https://cloud.githubusercontent.com/assets/17725108/13603966/82a4c3ba-e538-11e5-8944-ffec87f09f3f.png)
![btn_google _dark_normal_ios 3x - copy](https://cloud.githubusercontent.com/assets/17725108/13603968/846517f4-e538-11e5-8e8b-cbaa40502834.png)
![btn_google _dark_normal_ios 3x](https://cloud.githubusercontent.com/assets/17725108/13603970/86336568-e538-11e5-93fe-fbc99043b819.png)
![btn_google _light_normal_ios - copy](https://cloud.githubusercontent.com/assets/17725108/13603971/8804ce36-e538-11e5-9fb2-552b1fd47724.png)
![btn_google _light_normal_ios](https://cloud.githubusercontent.com/assets/17725108/13603975/89a4a59a-e538-11e5-9b53-c6d5ddbb96fe.png)
![btn_google _light_normal_ios 2x - copy](https://cloud.githubusercontent.com/assets/17725108/13603977/8b624964-e538-11e5-9960-6754a35c2f81.png)
![btn_google _light_normal_ios 2x](https://cloud.githubusercontent.com/assets/17725108/13603981/8d1523e4-e538-11e5-9088-06713ab8a0c1.png)
![btn_google _light_normal_ios 3x - copy](https://cloud.githubusercontent.com/assets/17725108/13603985/8f56be2e-e538-11e5-9eff-1f13b4b18791.png)
![btn_google _light_normal_ios 3x](https://cloud.githubusercontent.com/assets/17725108/13603988/914390d6-e538-11e5-8eca-21130ed1a1c1.png)

**Comment by GVPenni** [comment]
Thanks!!

**Comment by rolficak** [comment]
[social-icons-default-1603.zip](https://github.com/EDMdesigner/editor-issues/files/184020/social-icons-default-1603.zip)

New social icon set. Will update our dashboard as well soon.
