### ISSUE TITLE
Color Picker german localization issue

### ISSUE THREAD

**Issue by sines99** [EDMdesigner/editor-issues#21]
Hi there,

we have an issue with the colorpicker. If there are more than 5 colors are used, the title shifts up, so that it is not possible any more to enter own values.
Check out the screenshots:

![edm01](https://cloud.githubusercontent.com/assets/17900334/13841457/5b319c48-ec29-11e5-9a34-77c01c240676.png)
![edm02](https://cloud.githubusercontent.com/assets/17900334/13841458/5b4e1d3c-ec29-11e5-8820-985843323e03.png)

Workarround:
- Change the localization "**Zuletzt verwendete Farben:**" to "**Zuletzt verwendet:**"

Thanks.

**Comment by balintsoos** [comment]
Thank you for reporting this issue, we will investigate and fix it soon.

**Comment by balintsoos** [comment]
This issue has been resolved. We will release next version of the editor in the upcoming days.

**Comment by sines99** [comment]
_PUSH!_

pls release the fixed version. waiting since more than one month.

thx

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
