### ISSUE TITLE
Problem with editing RTL text

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#26]
Our client has a problem with editing right-to-left text:

"We need to change punctuation marks in footer according to customer's scheme: http://postimg.org/image/qvqujwsyp/. But marks are put to another line automatically. Please take a look at screencast: http://screenshots.ftpes.ru/Screencast_13-25_04-04-2016.mp4 "

Please let me know if we can do anything to make it work or is it a bug and we should wait for the fix?

**Comment by rolficak** [comment]
We don't support right to left languages in the editor. Unfortunately the WYSIWYG module is not prepared for that properly. 

I would advise you to copy paste the text with the required punctuation to the editor - including line breaks, spaces, etc. This way hopefully the format will stay the same.

**Comment by agnieszkakowalska** [comment]
Our client says it's not working for him unfortunately... 
Is there any chance of supporting RTL in the future?

**Comment by rolficak** [comment]
![kepernyofoto 2016-04-05 - 16 01 36](https://cloud.githubusercontent.com/assets/6140317/14284403/b4202cfc-fb47-11e5-872c-bc310b457074.png)

I could still easily add the !!! and normal Latin characters to the editor. 
So there might be something wrong with the formatting of the original text, that's copied. 

Try to copy unformatted plain text and add the line breaks with the editor. 

In my above case I copied text from here http://generator.lorem-ipsum.info/_arabic in HTML format, and the WYSIWYG worked like a charm (even if I understood nothing from the text).
