### ISSUE TITLE
Stuck after selecting 'Defaults' tab

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#29]
If you select an element (example: image) 
![image](https://cloud.githubusercontent.com/assets/18616807/14825949/c5b2c488-0bd3-11e6-85a3-4646570bf996.png)

Then select the Defaults tab

Then go back to Content - the header tab changes to 'Content' but the information shown belongs to 'Defaults'.

![image](https://cloud.githubusercontent.com/assets/18616807/14825998/f1a8d780-0bd3-11e6-9597-86b38069d52c.png)

The same issue happens if you select 'Elements' after having selected 'Defaults', or if you move from the Content tab to the Elements tab and then back to Content.

This is with all controls configured on the right together (see example below with Content selected, showing Elements options).
![edm_support_1](https://cloud.githubusercontent.com/assets/18616807/14845502/7ebef14a-0c56-11e6-9f82-6e59de057956.JPG)

**Comment by GVSupport** [comment]
Looks like this may be the same as issue #18 (https://github.com/EDMdesigner/editor-issues/issues/18). I can't recreate it on the trial template on edmdesigner.com, only our integrated version - has the version with that fix been released?

**Comment by gyulanemeth** [comment]
Hello,

yes, we realized as well, that there are some cases when it's still happening. Working on it, will fix very soon.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624
