### ISSUE TITLE
Russian localization problem

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#3]
Hi Gyula/Roland,

How are you both? Hope all is well. Looks like you’ve been pretty busy recently, I have applied your latest editor version to our installs and I must say it looks great! 

Just one tiny thing I spotted which has to do with text styling (in Russian UI only) and displaying tabs if you have menu elements positioned on the right (our preference). See screenshot attached, the words “Содержимое” (Content) and “По умолчанию” (Defaults) are too long and the third tab falls over as you can see. If you change the wording this solves the styling issue, so if you could update it with the following that would be great.

Instead of “Содержимое” – replace with “Контент”
Instead of “По умолчанию” – replace with “Основные”

Hope all makes sense and again congrats on a new editor version!

Regards
Nik

**Comment by gyulanemeth** [comment]
We have changed the values, so it won't break the iconsRight layout.

**Comment by agnieszkakowalska** [comment]
Our Russian partner suggested it would be better to replace “По умолчанию” with "Стандартные" or even "По умолч." to keep the meaning. What do you think?

**Comment by rolficak** [comment]
The shorter the better. :+1: note: We don't speak Russian so have no idea :) 
We received the above values from a Russian partner as well.

**Comment by agnieszkakowalska** [comment]
Yes, I guess ;) Can you double check with them if it's okay? We received information that “Основные” doesn't have the exact meaning.

**Comment by nikbirukov** [comment]
It basically needs to be shorter that's all, i.e Instead of “Содержимое” – replace with “Контент” and  Instead of “По умолчанию” – replace with “Основные” these are the same meanings if you ask me. If other partner finds it confusing you can just shorten the second one to “Instead of “По умолчанию” – replace with “По умолч.” should work as well.

**Comment by agnieszkakowalska** [comment]
Great, let's go with "По умолч." then. Thank you.

**Comment by gyulanemeth** [comment]
https://github.com/EDMdesigner/editor-issues/releases/tag/r20160219
