### ISSUE TITLE
Opening editor first time for a template gives "Uncaught Error, no language package found!"

### ISSUE THREAD

**Issue by danieledler** [EDMdesigner/editor-issues#32]
When I first open a template for editing, the iframe doesn't load its content but halts on this error:

![image](https://cloud.githubusercontent.com/assets/7313550/15010606/3ef027cc-11ed-11e6-81e2-82717b938283.png)

When I go back and try to open the editor again, it works. This is the last call:

``` javascript
function getMyL10nPackage(vmKey) {
  if(!window.languagePackage) {
    throw "Error, no language package found!";
  }
```

**Comment by agnieszkakowalska** [comment]
Hi, I also remember noticing such error twice I believe, but it was not replicable on my side unfortunately - after refreshing the page it worked fine.

**Comment by danieledler** [comment]
Yes, it always work if I reload the page, which makes it hard to reproduce. It's not every time for a new template either, but it has happened several times for me, and that case should be handled by the editor by either showing some error feedback that asks the user to try again, or preferably by ensuring that window.languagePackage is defined or else define it.

**Comment by gyulanemeth** [comment]
Can you give me access to an environment, where it happens frequently? That would help a lot!

**Comment by danieledler** [comment]
When it happened frequently, it was usually the first time I tried to edit a template after I logged in (i.e. after I requested a new access token). The workflow was to first createFromDefaults and then open the editor for the new template.

I can't manage to reproduce it now unfortunately, so I would suggest to track it in your code from the stack trace above to make sure that window.languagePackage always get's set correctly if that is a requirement, or at least try to capture and handle possibly throwed errors somehow on your side. I'm sorry I can't help more than that.

**Comment by iamgaborgithub** [comment]
Dear Daniel,

I’m Gábor from edmdesigner.com. I organize our public Github issues and close this ticket because it looks outdated. If you do not agree with it please leave a comment and I’ll be in touch.

If you have any new issues or feedback to share then please don’t hesitate and open a new ticket or send us an email to support@edmdesigner.com.

I hope you are well.

Best regards,
Gábor Kovács
Project Manager @ edmdesigner.com
