### ISSUE TITLE
"No projectId given!!" for /json/project/updateInfo

### ISSUE THREAD

**Issue by danieledler** [EDMdesigner/editor-issues#33]
I'm trying to update the title for a project but I get the response

``` javascript
{ "err": "No projectId given!!" }
```

In the docs, you have required parameter field `data` of type `Project`, where the `Project` model has an `_id` field. So I tried sending the data as

``` javascript
{
  _id: "5729c3528a95db2a23f9fc16",
  title: "My new title"
}
```

For the `/json/project/createFromDefaults` route, this works, but that route also has `_id` next to `data` as required parameters in the docs.

Looking at the JS API, the jsonp request doesn't call `/jsonp/project/updateInfo` as in the docs, but `/jsonp/project/updateInfo/:projectId`, so I also tried `json/project/updateInfo/5729c3528a95db2a23f9fc16` but that resulted in a `404` response.

**Comment by gyulanemeth** [comment]
Hello,

well, these routes are weird a little bit. If you use JSONP, you should use /jsonp/project/updateInfo/:id but if you use the JSON, then you have to use /json/project/updateInfo and put a "projectId" field to the request. I know it's very ugly... It has historical reasons... :/

**Comment by danieledler** [comment]
Hi!
Thanks, that works! (I tried combinations with projectId too, at least adding it in the url, but I must have missed setting it in the body.)
