### ISSUE TITLE
No spell check available

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#34]
A spell checker would be great, are you planning this already?

**Comment by gyulanemeth** [comment]
Hello,

it's possible to enable the browser's spell checker. If that's enough, we can enable it soon.

**Comment by GVSupport** [comment]
Hi Gyulanemeth, 

That's not really a suitable solution for us. Ideally we'd like to see a spell check in the WYSIWYG text editor, or as an option in the Content on the right hand side. 

Thanks,
Lien

**Comment by gyulanemeth** [comment]
Unfortunately this kind of feature is not on our roadmap.

**Comment by leggomuhgreggo** [comment]
Hey, I came here because some of my users are asking about spellcheck. I think browser spellcheck would be perfectly fine. @gyulanemeth is it still possible to get that wired up without too much difficulty? Perhaps an admin toggle? Thanks!

**Comment by leggomuhgreggo** [comment]
Also, is there a formal road map somewhere. Would love to keep up with it. Thanks

**Comment by balintsoos** [comment]
CKEditor Spell checker documentation: http://docs.ckeditor.com/#!/guide/dev_spellcheck

**Comment by GVSupport** [comment]
@balintsoos looks interesting, is this something you'll be adding to the editor soon?
