### ISSUE TITLE
Edit bullet point problem

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#36]
Dear Support,

We found that when using bullet points in text block, the points are not alighted properly:
![2016-05-17_14-33-13](https://cloud.githubusercontent.com/assets/5524183/15313196/55568214-1c3c-11e6-8ece-3d8d3bae9f61.png)

But the format is correct after export HTML:
![2016-05-17_14-34-19](https://cloud.githubusercontent.com/assets/5524183/15313216/754f2008-1c3c-11e6-89a7-dad40715ad05.png)

Although the final result is correct, we still hope that the bullet point effect will be consistent with exported html.

Please advise if this can be fixed.

Thanks.

**Comment by gyulanemeth** [comment]
Hello,

this is happening because we change the bullet-points to tables when we generate the html, but while editing it's a valid look, because there are no tables behind. I think it's actually not fixable.

**Comment by leggomuhgreggo** [comment]
Out of curiosity, why to you change them to tables? Do lists get some
undesirable client render?

**Comment by gyulanemeth** [comment]
Yes, simple lists are not stable enough. This way we can ensure that bulletpoint lists will look nice on all clients.

**Comment by leggomuhgreggo** [comment]
Understandable. I appreciate the answer. Looks like in the editor the default list styles are being overridden and dropping the indentation by setting `ul,ol { padding:0}`.

Assuming the default indentation is problematic for some reasons and it's necessary to override it in the editor styles with the counter for the ol and the `list-style: disc inside` for the ul, you could add this to recreate that indentation:

```
ol,ul{
  padding-left: 40px;
  list-style:none; //for both now

  li:before{
    position: absolute;
    left: 0;
    margin-left: -18px;
  } 
}

ul li:before{
  content:'• '
}
```

[codepen](http://codepen.io/leggomuhgreggo/pen/ZObNBQ?editors=0100)
