### ISSUE TITLE
French localization problem

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#43]
Dear Gyula,

Hope you're well.

We identified a new issue on a radio button for french translation :
https://www.dropbox.com/s/y3yyhuizw3ctkic/Capture%20d%27%C3%A9cran%202016-06-16%2011.29.18.png?dl=0

Could you please resend us the translation tools link so we can update these strings ?

Best regards,
## 

Faly M.

---

Hello Guyla,

Otherwise you can just set the translation to : On / Off Instead of « Activer / Désactiver »
I think the french accents cause the problem.

There are 2 translation concerned : hide on mobile and reorder on mobile.
And change « Réorganiser les colonnes sur mobile » for « Réorganiser sur mobile » because texte is to long.

Actually : 
![unnamed](https://cloud.githubusercontent.com/assets/1527824/16189763/4bfb24a8-36dc-11e6-9eb8-8fb293ef74d7.png)

And we need :
![unnamed 1](https://cloud.githubusercontent.com/assets/1527824/16189768/5308680a-36dc-11e6-8bfb-c89533d4821b.png)

Perhaps can you make the modification in your side easily ? It is relatively urgent (we can’t desactive the function « reorder on mobile »)

Thank you for your help.
Best regards,

Loïc

**Comment by falydev** [comment]
- hide-toggle-on => On
- hide-toggle-off => Off
- reorder-on-mobile-toggle => "Réorganiser sur mobile:"
- reorder-toggle-on => On
- reorder-toggle-off => Off

**Comment by gyulanemeth** [comment]
Thank you for the info, we will add it to the next release.

**Comment by gyulanemeth** [comment]
Fixed in: https://github.com/EDMdesigner/editor-issues/releases/tag/r20160624

**Comment by falydev** [comment]
Thanks

**Comment by falydev** [comment]
hide-desktop-toggle-on => On
hide-desktop-toggle-off => Off

**Comment by falydev** [comment]
@gyulanemeth Please reopen this ticket, we have 2 localization issue. Thanks.

**Comment by falydev** [comment]
fullwidth-on-mobile-toggle-on => On
fullwidth-on-mobile-toggle-off => Off
