### ISSUE TITLE
Change translation of Complex element in Chinese

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#56]
Hi, in semantic meaning, there is an ambiguity in the name of the Complex element in Chinese.
Could you please change "已存混合元素" to "已存元素"?
![screenshot 3](https://cloud.githubusercontent.com/assets/17157918/18825618/9f78b6e2-83c9-11e6-9ba8-1c5fb9b0c251.png)

**Comment by gyulanemeth** [comment]
Thank you for reporting it. We will do it with some other fixes.

**Comment by agnieszkakowalska** [comment]
Hi, please let me know what is the status of this request.

**Comment by smiska** [comment]
This translation is available from the editor version r20170419.
