### ISSUE TITLE
Multicolumn pixel count

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/editor-issues#57]
There is  a serious issue with the multicolum, which is causing problems. Pixel count and percentace is adding up to more than 100% or 600 px. Because of this, emails are not presented in the intended way.

![multi 1](https://cloud.githubusercontent.com/assets/17139637/19069913/41a45f1a-8a29-11e6-853e-bcf65ffb8a43.JPG)
![multi2](https://cloud.githubusercontent.com/assets/17139637/19069914/41a775e2-8a29-11e6-8fbb-8f22b6151eff.JPG)

**Comment by rolficak** [comment]
Can you please provide reproduction steps? Since we never saw anything like
this.
ᐧ

Roland Pokornyik
CEO, Co-founder @ EDMdesigner.com

+36-70-608-4433

_Schedule http://www.meetme.so/Roland-EDMdesigner a Skype chat with me!_
