### ISSUE TITLE
Image in text - lorem ipsum around the image in ckEditor

### ISSUE THREAD

**Issue by gyulanemeth** [EDMdesigner/editor-issues#6]
Dear Gyula,

We have tried inserting a small image into text block by custom message:

However, by double clicking the image, there are some surrounding text in preview area:

Is it possible to remove those surrounding text?

Thanks.
![bug1](https://cloud.githubusercontent.com/assets/1527824/12880864/1e2607aa-ce45-11e5-882b-1c020ec4f87e.png)
![bug2](https://cloud.githubusercontent.com/assets/1527824/12880865/1e2aa3dc-ce45-11e5-865c-dff523c1fd39.png)

**Comment by gyulanemeth** [comment]
It's not a bug... It's dummy text. It's there to show how the text will wrap around the image.
We can disable it with this option:
config.image_previewText = ""

We have been asked to set it up in the next release, so we will do.

**Comment by gyulanemeth** [comment]
https://github.com/EDMdesigner/editor-issues/releases/tag/r20160219

**Comment by vyuva-17** [comment]
where i have to use this below option
config.image_previewText = ""
