### ISSUE TITLE
Multicolumn less than 10%

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#62]
Some of our customers need to create columns which could be less than 10 % of the full size of the column element. Now it is impossible.

![multicolumn](https://cloud.githubusercontent.com/assets/17157918/19932132/312df45a-a10f-11e6-8aff-161c9c7271a3.png)

Can you make it possible? There have been already many questions from our customers regarding that case.

**Comment by rolficak** [comment]
It's possible now as well. They only need to add an additional multicolumn
to the given column.

It's possible to embed multiple multi-column elements into each other.

Best,
ᐧ

Roland Pokornyik
CEO, Co-founder @ EDMdesigner.com

+36-70-608-4433

_Schedule http://www.meetme.so/Roland-EDMdesigner a Skype chat with me!_

**Comment by agnieszkakowalska** [comment]
Thank you Roland! I've passed this info to the customer ;)
