### ISSUE TITLE
{"errorMessage":"2016-12-29T10:34:08.451Z 51f5e1f3-cdb2-11e6-bd13-b900ba731a80 Task timed out after 4.00 seconds"}

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/editor-issues#67]
Hi,
One of our clients is experiencing issues with some of their newsletters (with some of their NL working fine) of not being able to show a preview or to send preview. Please help.

Thanx,

Richard

{"errorMessage":"2016-12-29T10:34:08.451Z 51f5e1f3-cdb2-11e6-bd13-b900ba731a80 Task timed out after 4.00 seconds"}

**Comment by gyulanemeth** [comment]
➤ gyula commented:
Hello Richard,

it happens because of a ReDoS bug in our generator. Please attach the JSON, so we can start the investigation.

**Comment by RichardMailcamp** [comment]
Hi

There you go. (same issue apparently, 23 days later). Thanx for the help in advance



[58887c4931abbe7242c4c43c.docx](https://github.com/EDMdesigner/editor-issues/files/729835/58887c4931abbe7242c4c43c.docx)

**Comment by RichardMailcamp** [comment]
Hi.

Issue resolved. Client pasted HTML (text) from her site which caused the crash. Suddenly i remembered a similar issue....

Thanx anyway :)
