### ISSUE TITLE
Editor keeps loading

### ISSUE THREAD

**Issue by Mailcamp** [EDMdesigner/editor-issues#7]
Hi,

We have a customer where the editor page keeps loading.
Strange thing is that we can reach that page with his own login (where he could'nt).

His colleague on the same network has the same loading issue.

Do you have any idea what could be the problem?

Regards

Silas de Rooy
![edm-bug](https://cloud.githubusercontent.com/assets/16222817/12892418/5374e61e-ce8c-11e5-9d18-717a4afc960f.jpg)

**Comment by gyulanemeth** [comment]
Hello,

did it happen only once or does it happen all the times with some of your clients?
