### ISSUE TITLE
Social Share element uses placeholder text when URL option set to "campaign's"

### ISSUE THREAD

**Issue by GVSupport** [EDMdesigner/editor-issues#74]
One of our customers noticed that when they insert a 'Social Share' element to a design and set the URL to "campaign's", the social links are using the placeholders "##textToShare##" and "##linkToShare##" (the full links are below).

![image](https://cloud.githubusercontent.com/assets/18616807/24035633/587a4f88-0aee-11e7-844f-c0ba8ddb799f.png)

I assume there is some configuration needed on our end in order to set these placeholders to something meaningful for the campaign. Do you have a working example of how to configure this?

Also, is there a way we can disable this option so users can only see the "custom" option?

Facebook: 

"https://www.facebook.com/dialog/return/close?error_code=100&error_message=href+should+represent+a+valid+URL#_=_"

Twitter:

"https://twitter.com/intent/tweet?text=%23%23textToShare%23%23%3A%20%23%23linkToShare%23%23"

LinkedIn: 

"https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2FshareArticle%3Ftitle%3D%2523%2523textToShare%2523%2523%26mini%3Dtrue%26url%3D%2523%2523linkToShare%2523%2523"

Email:

Creates an email to ##emailToSend##, subject ##textToShare## and content ##textToShare##: ##linkToShare##

**Comment by smiska** [comment]
Basically, what you would need to do here is a [string replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace), in which you switch ##textToShare## and ##linkToShare## to something meaningful. It may also help to take a look at our examples on implementing similar elements, like [Custom Strings](https://github.com/EDMdesigner/EDMDesigner-API-Example-PHP-Admin).
Disabling the default behavior would require developing a custom implementation of this toolbox. In case you require this functionality, I would suggest to contact our [main email address](info@edmdesigner.com).
Is there anything else I can help you with?
