### ISSUE TITLE
Designer "jumps" when user starts to edit large text.

### ISSUE THREAD

**Issue by agnieszkakowalska** [EDMdesigner/editor-issues#83]
Problem noticed on Chrome 58.0.3029.110 (64-bit) in resolution 1366x768. 

I added large text box between several other elements. When focus was set on element other then big text I scrolled the designer to a position where the text covered whole designer space. Then I double clicked the text to get a focus and edit it. Designer displayed the editor toolbar over the text so it had to scroll up - from user's perspective it is a sudden jump from the place where he wanted to edit the text. 

It would be better if in such case editor appeared near the place where user clicked. 
Screencast attached.
[edm.zip](https://github.com/EDMdesigner/editor-issues/files/1037710/edm.zip)

**Comment by smiska** [comment]
Thanks for reporting the issue and the provided environment info. This phenomenon happens because of some sort of default settings of the WYSIWYG editor we use. Is this a problem that you often encounter during your daily production?

**Comment by agnieszkakowalska** [comment]
Yes, unfortunately. We already received reports from couple of our most important clients that work with large blocks of text and for them that is a constant problem.

**Comment by smiska** [comment]
Hi @agnieszkakowalska , in one of our previous updates (r20170628-fix) we updated the WYSIWYG editor's version. In that new editor, this jumping behavior is not present. I hope you can confirm and with the new editor you'll have better experience.

**Comment by agnieszkakowalska** [comment]
Thank you!
