### ISSUE TITLE
Simplified Chinese language pack problem

### ISSUE THREAD

**Issue by confettidc** [EDMdesigner/editor-issues#84]
Dear Support,

When we tried to use Simplified Chinese language pack (zh) for editor interface, EDMdesigner prompt errors as below:
![default](https://cloud.githubusercontent.com/assets/5524183/26613715/b62bab3c-45ee-11e7-8180-58f9cf7a630f.png)

Please help check what the problem is, thanks.

**Comment by smiska** [comment]
Hi, thanks for contacting us with this issue.

It seems that you are referring to the language pack with incorrect addresses. The correct addresses for this editor version would be the following:
[https://api-static.edmdesigner.com/r20160624/i18n/langPack_zh-HANS.js](https://api-static.edmdesigner.com/r20160624/i18n/langPack_zh-HANS.js), [https://api-static.edmdesigner.com/r20160624/i18n/l10n_zh-HANS.js](https://api-static.edmdesigner.com/r20160624/i18n/l10n_zh-HANS.js). 

I hope it helps. Please tell us if you need more assistance.
