### ISSUE TITLE
display problem in outlook

### ISSUE THREAD

**Issue by RichardMailcamp** [EDMdesigner/editor-issues#9]
## -Hi,

-We encountered a problem with a file from one of our clients. Ive added the zipped JSON and a couple of screenshots that illustrate the issue, as we haven't encountered it before. Maybe it's outlook related, seeing that the template is displayed the right way in a browser window, but as this is email marketing, i thought i'd at least mention it. 
[56a754209399361a4d8801b0.zip](https://github.com/EDMdesigner/editor-issues/files/126683/56a754209399361a4d8801b0.zip)
![ud capture right](https://cloud.githubusercontent.com/assets/17139637/12981993/5537ce86-d0e3-11e5-8bc1-f2fbb69b2fa0.JPG)
![ud capture wrong outlook](https://cloud.githubusercontent.com/assets/17139637/12981994/555d3554-d0e3-11e5-8f7d-cbf465e11d13.JPG)

**Comment by gyulanemeth** [comment]
Hello,

can you tell me the exact email clients on which it occured?

**Comment by gyulanemeth** [comment]
Also, please use the generator repository for issues which are related with the html output.

**Comment by RichardMailcamp** [comment]
Ok, my apologies. It was on outlook
