### ISSUE TITLE
Social Follow Email label

### ISSUE THREAD

**Issue by samtlewis** [EDMdesigner/editor-issues#91]
When adding a social follow element and choosing the "Email" option from the list, unlike the other options, the label is missing "Text" as in "Link Text".
![image](https://user-images.githubusercontent.com/1706265/29824243-d056502e-8c85-11e7-9016-ea25a6bb054b.png)

**Comment by smiska** [comment]
Hi @samtlewis . We fixed the Social Follow Toolbox's label in the latest release "r20170926". Thank you for your feedback.
