### ISSUE TITLE
Social Follow/Share mobile rendering request

### ISSUE THREAD

**Issue by samtlewis** [EDMdesigner/editor-issues#92]
We'd like to see an option with the social follow/share icons to not stack these on mobile. We'd like to see this option added as a feature like in the Multicolumn element. So users can turn on/off the stacking of the social icons.

**Comment by smiska** [comment]
Hi Sam, we'll discuss this in the team and I'll get back to you soon how and when we could roll this feature out.

**Comment by smiska** [comment]
We discussed our schedule and we can make this update by around the second part of October. I hope this timing works for you.

**Comment by samtlewis** [comment]
Smiska,

Just checking to see if this is still on track for this month. Thanks.

**Comment by smiska** [comment]
Hi Sam, I'm sorry for not updating you before, I was ill. We can switch the current settings of the social share element from stacking to non-stacking for newly created templates. Should we proceed with this?Implementing a switch button unfortunately exceeds our current development possibilities.

**Comment by samtlewis** [comment]
smiska,

Well we were hoping for a user selectable setting but if that is not possible, then yes we would prefer that the social share/follow icons do not stack on mobile.

**Comment by smiska** [comment]
Hi Sam,

In the end, we implemented your idea and made reorder selectable. It’s set to reorder on mobile by default as it is more stable with layout structure. You have a checkbox for disabling the reordering in the layout editor toolbox.
![layouteditor](https://user-images.githubusercontent.com/16736043/32613899-547c6dec-c56c-11e7-99aa-4fc3de7c1963.png)

**Comment by samtlewis** [comment]
@smiska Love the new addition but it doesn't quite work right. See the attached screencast for a demo.

1. Add Social Share/Follow element
2. Uncheck the "Reorder columns on mobile"
3. icons are shown as side by side
4. Change one of the selected social networks (Facebook to Linked for instance)
5. Icons/text are updated in the content tab and the html but the icons revert to being stacked regardless of the state of the Reorder checkbox

[social-share-follow-stacking.swf.zip](https://github.com/EDMdesigner/editor-issues/files/1458791/social-share-follow-stacking.swf.zip)

**Comment by smiska** [comment]
Hi Sam, with continuously generated live preview the update really not delivers the value it's supposed to. It made sense before to default to reorder behavior on any update, but know that I know exactly how you use it doesn't anymore. I'll fix it, so the chosen reorder mode will be persistent.  Thanks for the feedback.

**Comment by samtlewis** [comment]
@smiska, any update?

**Comment by smiska** [comment]
I'm deeply sorry for the late reaction. I'm still working on the fix as there's still a minor bug that needs to be handled. I hope to release the update this week. I'll get back to you when I could figure out the solution and the update is available. Sorry for any inconvenience.

**Comment by smiska** [comment]
Hi @samtlewis , I'm sorry for the delayed follow up on the editor release. We encountered many barriers during the process. There's a new release available in the API dashboard (r20180103). It fixes the behavior of social icons' reordering. I hope you'll find it working as expected.

**Comment by samtlewis** [comment]
This works great and addresses our needs perfectly. Thanks. Closing the issue
