### ISSUE TITLE
Social Share Background image option

### ISSUE THREAD

**Issue by samtlewis** [EDMdesigner/editor-issues#93]
After adding a social share element, the Jump to Gallery option to assign a background image does not work. Selecting background image and the jump to gallery button does not activate the gallery so you can't assign an image.

**Comment by smiska** [comment]
Hi @samtlewis , would you need this feature? Adding background image in the social share element doesn't seem a useful use case. We probably disabled the "Jump to Gallery" option as a temporary solution - as hiding this settings would require building a new toolbox solely for the social share element.

**Comment by samtlewis** [comment]
No I don't see any reason to be able to assign images. I would just ask that a non-functional item be removed.

**Comment by smiska** [comment]
Thanks @samtlewis for the clarification. We added it to our bug list, but the improvement would need some time. I ask for your kind patience.

**Comment by smiska** [comment]
Hi @samtlewis , The editor release r20180103 was updated based on your request, so the non-functional background image settings will not show.
