### ISSUE TITLE
Responsive preview not accurate in Firefox

### ISSUE THREAD

**Issue by samtlewis** [EDMdesigner/editor-issues#96]
Actual mobile versions do render correctly but when viewing a preview iframe of a responsive email in Firefox columns are not stacking properly.

We have a side by side view of the editor and a real time preview where this issue is seen only in Firefox. This doesn't affect the actual email but does cause concern by our clients when previewing emails.

I've attached a screenshot that shows our side by side view using Firefox. You can see in the preview on the right that the columns are not stacking. I've noted that in the media query that there is a float:none; rule but without an !important this seems to be overridden. When I manually add the !important the columns do stack correctly.

![edm-firefoxpreview](https://user-images.githubusercontent.com/1706265/31195234-70f925e4-a8fe-11e7-89a3-09415deac96b.png)

**Comment by smiska** [comment]
Hi @samtlewis, could you provide a projectId so we can look into the template?
Also I would need to know what's the firefox version and where does this preview come from?
Thanks.

**Comment by samtlewis** [comment]
Sorry this looks to be an issue with how we are generating the preview and not with any of the EDM code. I'll close this issue now.
