### ISSUE TITLE
502 Bad Gateway - URGENT! (all our customers has this problem)

### ISSUE THREAD

**Issue by Silassiai** [EDMdesigner/editor-issues#98]
![image](https://user-images.githubusercontent.com/18419961/31878443-678d25ba-b7da-11e7-9800-a141a55c4132.png)

Hi,

Kan you please fix this ASAP???

**Comment by gyulanemeth** [comment]
Hello,

thank you for reporting this. We are aware of the problem and working on the fix.

**Comment by Silassiai** [comment]
Hi gyula,

The problem is fixed. Thanks for the fast response!

**Comment by gyulanemeth** [comment]
Hello Silas, thank you for confirming it.
