### ISSUE TITLE
Social Share Element Labels not updating on change

### ISSUE THREAD

**Issue by samtlewis** [EDMdesigner/editor-issues#99]
The attached video shows the issue. This was taken in the EDM demo on your site.

Add a Social Share element.
Change the social network using the drop down and the icon changes but the label does not.
Luckily the icon and text in the template do change and if you click out of the element and re-select it, the social icons/labels are correct both in the template and the content tab.

[SocialShareLabelNotUpdating.mov.zip](https://github.com/EDMdesigner/editor-issues/files/1408979/SocialShareLabelNotUpdating.mov.zip)

**Comment by smiska** [comment]
​Hi Sam,

We released a new editor today (r20171109).
A fix for this feature was included in it. I hope you’ll find it working properly now.
Thank you for your patience.

**Comment by samtlewis** [comment]
Just tested this fix. Looks good. Thanks.
